export const dailyWords = [
  { word: "abandon", options: ["bỏ rơi", "bắt đầu", "thành công", "giữ gìn"], answer: "bỏ rơi" },
  { word: "accommodate", options: ["đáp ứng, chứa được", "làm khó", "giữ nguyên", "từ chối"], answer: "đáp ứng, chứa được" },
  { word: "agenda", options: ["chương trình nghị sự", "hợp đồng", "bản báo cáo", "hóa đơn"], answer: "chương trình nghị sự" },
  { word: "allocate", options: ["phân bổ", "giữ lại", "tiêu hao", "bỏ qua"], answer: "phân bổ" },
  { word: "annual", options: ["hàng năm", "hiếm khi", "tạm thời", "ngẫu nhiên"], answer: "hàng năm" },
  { word: "appraisal", options: ["sự thẩm định", "sự cải tiến", "sự thất bại", "sự hợp tác"], answer: "sự thẩm định" },
  { word: "assemble", options: ["lắp ráp", "tách rời", "giấu đi", "phá hủy"], answer: "lắp ráp" },
  { word: "audit", options: ["kiểm toán", "tuyển dụng", "lập kế hoạch", "tiếp thị"], answer: "kiểm toán" },
  { word: "benevolent", options: ["nhân từ", "ác độc", "giàu có", "khó khăn"], answer: "nhân từ" },
  { word: "candidate", options: ["ứng viên", "khách hàng", "giám đốc", "giáo viên"], answer: "ứng viên" },
  { word: "collaborate", options: ["hợp tác", "cạnh tranh", "tách biệt", "bỏ qua"], answer: "hợp tác" },
  { word: "confidential", options: ["bí mật", "công khai", "bắt buộc", "tạm thời"], answer: "bí mật" },
  { word: "consolidate", options: ["củng cố, hợp nhất", "chia tách", "giảm bớt", "trì hoãn"], answer: "củng cố, hợp nhất" },
  { word: "crucial", options: ["quan trọng", "không quan trọng", "xa xôi", "giản đơn"], answer: "quan trọng" },
  { word: "deadline", options: ["hạn chót", "ngày nghỉ", "giờ làm việc", "khoảng thời gian"], answer: "hạn chót" },
  { word: "deduct", options: ["khấu trừ", "tăng thêm", "giữ nguyên", "thêm vào"], answer: "khấu trừ" },
  { word: "deficit", options: ["thâm hụt", "dư thừa", "tăng trưởng", "cân đối"], answer: "thâm hụt" },
  { word: "deteriorate", options: ["xấu đi, suy giảm", "ổn định", "cải thiện", "phát triển"], answer: "xấu đi, suy giảm" },
  { word: "endorse", options: ["chứng thực", "từ chối", "phê bình", "bỏ qua"], answer: "chứng thực" },
  { word: "evaluate", options: ["đánh giá", "bỏ qua", "chấp nhận", "trì hoãn"], answer: "đánh giá" },
  { word: "feasible", options: ["khả thi", "bất khả thi", "ngẫu nhiên", "tạm thời"], answer: "khả thi" },
  { word: "freight", options: ["hàng hóa vận chuyển", "doanh thu", "giấy phép", "lợi nhuận"], answer: "hàng hóa vận chuyển" },
  { word: "headquarters", options: ["trụ sở chính", "chi nhánh", "phòng họp", "nhà kho"], answer: "trụ sở chính" },
  { word: "inventory", options: ["hàng tồn kho", "doanh thu", "chi phí", "tài sản"], answer: "hàng tồn kho" },
  { word: "liaison", options: ["người liên lạc", "đối thủ", "chứng từ", "nhà cung cấp"], answer: "người liên lạc" },
  { word: "advocate", options: ["người ủng hộ", "đối thủ", "quan chức", "kẻ phản bội"], answer: "người ủng hộ" },
  { word: "allegation", options: ["cáo buộc", "bằng chứng", "chiến lược", "giải pháp"], answer: "cáo buộc" },
  { word: "ambiguous", options: ["mơ hồ", "rõ ràng", "chính xác", "tuyệt đối"], answer: "mơ hồ" },
  { word: "amendment", options: ["sự sửa đổi", "sự phá hủy", "sự bảo tồn", "sự thay thế"], answer: "sự sửa đổi" },
  { word: "analogy", options: ["sự tương tự", "sự khác biệt", "sự đối lập", "sự hỗn loạn"], answer: "sự tương tự" },
  { word: "anecdote", options: ["giai thoại", "tiểu thuyết", "bài diễn văn", "hồ sơ"], answer: "giai thoại" },
  { word: "applicable", options: ["có thể áp dụng", "không liên quan", "không hợp lệ", "bất khả thi"], answer: "có thể áp dụng" },
  { word: "arbitrary", options: ["tùy tiện", "hợp lý", "công bằng", "logic"], answer: "tùy tiện" },
  { word: "aspiration", options: ["khát vọng", "nỗi sợ", "sự thất bại", "sự miễn cưỡng"], answer: "khát vọng" },
  { word: "attain", options: ["đạt được", "từ bỏ", "tránh né", "làm hỏng"], answer: "đạt được" },
  { word: "attribute", options: ["thuộc tính", "sự việc", "vật chất", "tài nguyên"], answer: "thuộc tính" },
  { word: "authentic", options: ["xác thực", "giả mạo", "sai lầm", "thất bại"], answer: "xác thực" },
  { word: "autonomy", options: ["quyền tự trị", "nô lệ", "phụ thuộc", "thống trị"], answer: "quyền tự trị" },
  { word: "benchmark", options: ["chuẩn mực", "khuyết điểm", "sai lầm", "mục tiêu sai"], answer: "chuẩn mực" },
  { word: "bias", options: ["định kiến", "sự công bằng", "sự thật", "chân lý"], answer: "định kiến" },
  { word: "blatant", options: ["rõ ràng (mang tính xấu)", "kín đáo", "ẩn giấu", "bí mật"], answer: "rõ ràng (mang tính xấu)" },
  { word: "coherent", options: ["mạch lạc", "rời rạc", "mơ hồ", "hỗn loạn"], answer: "mạch lạc" },
  { word: "coincide", options: ["trùng hợp", "khác biệt", "đối lập", "chia rẽ"], answer: "trùng hợp" },
  { word: "commence", options: ["bắt đầu", "kết thúc", "tạm dừng", "gián đoạn"], answer: "bắt đầu" },
  { word: "compatible", options: ["tương thích", "mâu thuẫn", "xung đột", "trái ngược"], answer: "tương thích" },
  { word: "compensate", options: ["bồi thường", "tước đoạt", "trốn tránh", "làm hại"], answer: "bồi thường" },
  { word: "complement", options: ["bổ sung", "loại bỏ", "phá hủy", "tách biệt"], answer: "bổ sung" },
  { word: "compliance", options: ["sự tuân thủ", "sự nổi loạn", "sự chống đối", "sự bất đồng"], answer: "sự tuân thủ" },
  { word: "comprise", options: ["bao gồm", "loại trừ", "chấm dứt", "giảm bớt"], answer: "bao gồm" },
  { word: "conceive", options: ["hình dung, tưởng tượng", "quên đi", "giấu giếm", "bỏ qua"], answer: "hình dung, tưởng tượng" },
  { word: "confer", options: ["trao tặng, bàn bạc", "từ chối", "che giấu", "giữ lại"], answer: "trao tặng, bàn bạc" },
  { word: "contemplate", options: ["suy ngẫm", "phớt lờ", "từ chối", "quên lãng"], answer: "suy ngẫm" },
  { word: "contradict", options: ["mâu thuẫn", "ủng hộ", "xác nhận", "khẳng định"], answer: "mâu thuẫn" },
  { word: "conversely", options: ["ngược lại", "tương tự", "giống nhau", "song song"], answer: "ngược lại" },
  { word: "credibility", options: ["sự đáng tin cậy", "sự giả dối", "sự phản bội", "sự sai lầm"], answer: "sự đáng tin cậy" },
  { word: "crucially", options: ["một cách quan trọng", "không quan trọng", "ngẫu nhiên", "phụ"], answer: "một cách quan trọng" },
  { word: "cumulative", options: ["tích lũy", "giảm sút", "mất mát", "bỏ đi"], answer: "tích lũy" },
  { word: "dedicate", options: ["cống hiến", "phớt lờ", "bỏ cuộc", "phản bội"], answer: "cống hiến" },
  { word: "depict", options: ["miêu tả", "xóa bỏ", "làm mờ", "giấu đi"], answer: "miêu tả" },
  { word: "detain", options: ["giam giữ", "thả ra", "tự do", "giải phóng"], answer: "giam giữ" },
  { word: "diminish", options: ["giảm bớt", "tăng thêm", "mở rộng", "phát triển"], answer: "giảm bớt" },
  { word: "discretion", options: ["sự thận trọng", "sự bất cẩn", "sự ngu ngốc", "sự liều lĩnh"], answer: "sự thận trọng" },
  { word: "disseminate", options: ["phổ biến", "che giấu", "từ chối", "xóa bỏ"], answer: "phổ biến" },
  { word: "distort", options: ["bóp méo", "làm rõ", "xác minh", "khẳng định"], answer: "bóp méo" },
  { word: "eligible", options: ["đủ điều kiện", "không phù hợp", "bị cấm", "trái phép"], answer: "đủ điều kiện" },
  { word: "embark", options: ["bắt đầu (hành trình)", "kết thúc", "bỏ qua", "ngừng lại"], answer: "bắt đầu (hành trình)" },
  { word: "enforce", options: ["thi hành", "phớt lờ", "từ bỏ", "giấu đi"], answer: "thi hành" },
  { word: "enquire", options: ["hỏi thăm, điều tra", "che giấu", "phớt lờ", "từ bỏ"], answer: "hỏi thăm, điều tra" },
  { word: "entail", options: ["đòi hỏi, kéo theo", "loại bỏ", "từ chối", "giải thoát"], answer: "đòi hỏi, kéo theo" },
  { word: "equivalent", options: ["tương đương", "khác biệt", "đối lập", "ngược lại"], answer: "tương đương" },
  { word: "erroneous", options: ["sai lầm", "chính xác", "chuẩn xác", "đúng đắn"], answer: "sai lầm" },
  { word: "exceed", options: ["vượt quá", "giảm bớt", "thua kém", "tụt lại"], answer: "vượt quá" },
  { word: "feasible", options: ["khả thi", "bất khả thi", "hư cấu", "mơ hồ"], answer: "khả thi" },
  { word: "fluctuate", options: ["dao động", "ổn định", "cố định", "giữ nguyên"], answer: "dao động" },
  { word: "formulate", options: ["xây dựng (kế hoạch)", "hủy bỏ", "phá hoại", "giấu đi"], answer: "xây dựng (kế hoạch)" },
  { word: "framework", options: ["khung (cấu trúc)", "nội dung", "chất liệu", "chi tiết"], answer: "khung (cấu trúc)" },
  { word: "paradigm", options: ["mô hình", "nguyên tắc", "mục tiêu", "thói quen"], answer: "mô hình" },
  { word: "infrastructure", options: ["cơ sở hạ tầng", "tài nguyên", "vật liệu", "chi phí"], answer: "cơ sở hạ tầng" },
  { word: "viability", options: ["tính khả thi", "tính hợp pháp", "tính thẩm mỹ", "tính độc đáo"], answer: "tính khả thi" },
  { word: "sustainability", options: ["tính bền vững", "tính linh hoạt", "tính an toàn", "tính hiệu quả"], answer: "tính bền vững" },
  { word: "autonomy", options: ["quyền tự chủ", "quyền kiểm soát", "quyền sở hữu", "quyền lợi"], answer: "quyền tự chủ" },
  { word: "resilience", options: ["sức bật, khả năng phục hồi", "sự kiên nhẫn", "sức mạnh", "sự bền bỉ"], answer: "sức bật, khả năng phục hồi" },
  { word: "connotation", options: ["hàm ý", "ngữ pháp", "nghĩa gốc", "cách phát âm"], answer: "hàm ý" },
  { word: "implication", options: ["hàm ý", "kết luận", "bằng chứng", "giả định"], answer: "hàm ý" },
  { word: "coherence", options: ["tính mạch lạc", "tính sáng tạo", "tính phổ biến", "tính chính xác"], answer: "tính mạch lạc" },
  { word: "discrepancy", options: ["sự khác biệt", "sự trùng lặp", "sự tương đồng", "sự lựa chọn"], answer: "sự khác biệt" },
  { word: "feasibility", options: ["tính khả thi", "tính hợp lệ", "tính dễ hiểu", "tính phổ biến"], answer: "tính khả thi" },
  { word: "magnitude", options: ["độ lớn, tầm quan trọng", "chi tiết", "khoảng cách", "kích thước nhỏ"], answer: "độ lớn, tầm quan trọng" },
  { word: "precedent", options: ["tiền lệ", "hệ quả", "bằng chứng", "nguyên tắc"], answer: "tiền lệ" },
  { word: "repercussion", options: ["hệ quả", "nguyên nhân", "quy trình", "tác nhân"], answer: "hệ quả" },
  { word: "violation", options: ["sự vi phạm", "sự chấp thuận", "sự cho phép", "sự phát triển"], answer: "sự vi phạm" },
  { word: "conformity", options: ["sự tuân thủ", "sự phản đối", "sự khác biệt", "sự biến đổi"], answer: "sự tuân thủ" },
  { word: "exploitation", options: ["sự khai thác", "sự bỏ qua", "sự đầu tư", "sự nghiên cứu"], answer: "sự khai thác" },
  { word: "innovation", options: ["sự đổi mới", "sự kế thừa", "sự kết thúc", "sự bảo tồn"], answer: "sự đổi mới" },
  { word: "orientation", options: ["định hướng", "tập huấn", "địa hình", "cấu trúc"], answer: "định hướng" },
  { word: "diversity", options: ["sự đa dạng", "sự khan hiếm", "sự tương đồng", "sự thống nhất"], answer: "sự đa dạng" },
  { word: "alignment", options: ["sự sắp xếp thẳng hàng", "sự đối đầu", "sự cân bằng", "sự thay thế"], answer: "sự sắp xếp thẳng hàng" },
  { word: "articulation", options: ["sự diễn đạt rõ ràng", "sự học hỏi", "sự sao chép", "sự kiểm soát"], answer: "sự diễn đạt rõ ràng" },
  { word: "compliance", options: ["sự tuân thủ", "sự hợp tác", "sự đồng tình", "sự từ chối"], answer: "sự tuân thủ" },
  { word: "integrity", options: ["sự chính trực", "sự kết nối", "sự công bằng", "sự bảo mật"], answer: "sự chính trực" },
  { word: "credibility", options: ["độ tin cậy", "độ bền", "tính khả thi", "tính minh bạch"], answer: "độ tin cậy" },
  { word: "validity", options: ["tính hợp lệ", "tính sáng tạo", "tính phổ biến", "tính khách quan"], answer: "tính hợp lệ" },
  { word: "vulnerability", options: ["sự dễ tổn thương", "sự mạnh mẽ", "sự chủ động", "sự kiên nhẫn"], answer: "sự dễ tổn thương" },
  { word: "accountability", options: ["trách nhiệm giải trình", "quyền lợi", "khả năng thích ứng", "mục tiêu"], answer: "trách nhiệm giải trình" },
  { word: "cohesion", options: ["sự gắn kết", "sự linh hoạt", "sự đa dạng", "sự đối lập"], answer: "sự gắn kết" },
  { word: "proposition", options: ["đề xuất", "bằng chứng", "mệnh đề", "giả thuyết"], answer: "đề xuất" },
  { word: "speculation", options: ["sự suy đoán", "sự kiểm chứng", "sự bảo đảm", "sự xác thực"], answer: "sự suy đoán" },
  { word: "contradiction", options: ["sự mâu thuẫn", "sự xác nhận", "sự đồng thuận", "sự thống nhất"], answer: "sự mâu thuẫn" },
  { word: "hierarchy", options: ["hệ thống cấp bậc", "sự bình đẳng", "sự độc lập", "sự hỗn loạn"], answer: "hệ thống cấp bậc" },
  { word: "ambiguity", options: ["sự mơ hồ", "sự rõ ràng", "sự hợp lý", "sự mạch lạc"], answer: "sự mơ hồ" },
  { word: "incentive", options: ["sự khuyến khích", "sự phản đối", "sự phân tích", "sự kiểm soát"], answer: "sự khuyến khích" },
  { word: "compensation", options: ["sự bồi thường", "sự đầu tư", "sự phát triển", "sự kiểm tra"], answer: "sự bồi thường" },
  { word: "fluctuation", options: ["sự dao động", "sự ổn định", "sự bảo đảm", "sự tiến bộ"], answer: "sự dao động" },
  { word: "concession", options: ["sự nhượng bộ", "sự phản đối", "sự hợp tác", "sự ngăn cản"], answer: "sự nhượng bộ" },
  { word: "endeavour", options: ["nỗ lực", "thành công", "thói quen", "chiến lược"], answer: "nỗ lực" },
  { word: "hypothesis", options: ["giả thuyết", "lý thuyết", "chứng minh", "định nghĩa"], answer: "giả thuyết" },
  { word: "premise", options: ["tiền đề", "kết quả", "tài liệu", "sự kiện"], answer: "tiền đề" },
  { word: "convergence", options: ["sự hội tụ", "sự phân tán", "sự biến mất", "sự lệch lạc"], answer: "sự hội tụ" },
  { word: "divergence", options: ["sự khác biệt, sự phân kỳ", "sự kết hợp", "sự mạch lạc", "sự hội nhập"], answer: "sự khác biệt, sự phân kỳ" },
  { word: "viability", options: ["tính khả thi", "tính minh bạch", "tính khách quan", "tính bền bỉ"], answer: "tính khả thi" },
  { word: "subsidy", options: ["trợ cấp", "đầu tư", "chi phí", "thu nhập"], answer: "trợ cấp" },
  { word: "burden", options: ["gánh nặng", "cơ hội", "sự dễ dàng", "sự giàu có"], answer: "gánh nặng" },
  { word: "allocation", options: ["sự phân bổ", "sự đầu tư", "sự thu hồi", "sự tiết kiệm"], answer: "sự phân bổ" },
  { word: "expenditure", options: ["chi tiêu", "thu nhập", "dự trữ", "nguồn vốn"], answer: "chi tiêu" },
  { word: "retention", options: ["sự duy trì", "sự loại bỏ", "sự đổi mới", "sự thất thoát"], answer: "sự duy trì" },
  { word: "contingency", options: ["tình huống bất ngờ", "tình huống phổ biến", "kế hoạch chính", "mục tiêu"], answer: "tình huống bất ngờ" }
];